name: Run Imaging Cloud CLI
env:
  version: 1
on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  run-imaging-cloud-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run IL-CLI
        run: | 
          cd ${{github.workspace}}
          docker run -e IMAGING_CLOUD_API_KEY=${{secrets.IMAGING_CLOUD_API_KEY}} -e IMAGING_CLOUD_ACTION_FILE_VERSION=${{env.version}} -e IMAGING_CLOUD_URL="http://imaging-dev.castsoftware.io/"  -v $(pwd):/home/carl/extras/source castbuild/imaging-cloud-action:dev
